import React from 'react';

import type {ReactElement} from 'react';

export function IconClose(props: React.SVGProps<SVGSVGElement>): ReactElement {
	return (
		<svg
			{...props}
			width={'32'}
			height={'32'}
			viewBox={'0 0 32 32'}
			fill={'none'}
			xmlns={'http://www.w3.org/2000/svg'}>
			<rect
				x={'6'}
				y={'22'}
				width={'4'}
				height={'4'}
				fill={'currentcolor'}
			/>
			<rect
				x={'10'}
				y={'18'}
				width={'4'}
				height={'4'}
				fill={'currentcolor'}
			/>
			<rect
				x={'14'}
				y={'14'}
				width={'4'}
				height={'4'}
				fill={'currentcolor'}
			/>
			<rect
				x={'18'}
				y={'18'}
				width={'4'}
				height={'4'}
				fill={'currentcolor'}
			/>
			<rect
				x={'22'}
				y={'22'}
				width={'4'}
				height={'4'}
				fill={'currentcolor'}
			/>
			<rect
				x={'10'}
				y={'10'}
				width={'4'}
				height={'4'}
				fill={'currentcolor'}
			/>
			<rect
				x={'6'}
				y={'6'}
				width={'4'}
				height={'4'}
				fill={'currentcolor'}
			/>
			<rect
				x={'18'}
				y={'10'}
				width={'4'}
				height={'4'}
				fill={'currentcolor'}
			/>
			<rect
				x={'22'}
				y={'6'}
				width={'4'}
				height={'4'}
				fill={'currentcolor'}
			/>
		</svg>
	);
}
